testing with folder

diff --git a/.github/workflows/tf-plan.yml b/.github/workflows/tf-plan.yml
--- a/.github/workflows/tf-plan.yml
+++ b/.github/workflows/tf-plan.yml
@@ -1,3 +1,40 @@
+# name: "Terraform-Plan-Infra-Release"
+
+# on:
+#   push:
+#     branches:
+#       - dev_branch
+
+# jobs:
+#   terraform:
+#     name: "Terraform"
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout_repo_into_GH_RUnner
+#         uses: actions/checkout@v2
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init
+
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'push'
+#         run: terraform plan -out=tfplan -no-color 
+#         continue-on-error: true
+
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+
+
+
 name: "Terraform-Plan-Infra-Release"
 
 on:
@@ -19,16 +56,8 @@ jobs:
         with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
-
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'push'
-        run: terraform plan -out=tfplan -no-color 
-        continue-on-error: true
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      - name: Deploy Linux VM
+        run: |
+          cd terraform/linux-vm
+          terraform init
+          terraform apply -auto-approve
